version: '2'

services:

    php:
        container_name: students_php
        build: ./php-fpm
        volumes:
            - ./../:/var/www/symfony
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql

    web:
        image: nginx:latest
        container_name: students_nginx
        ports:
            - "80:80"
        volumes:
            - ./../:/var/www/symfony
            - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/logs/:/var/log/nginx/
        links:
            - php
        depends_on:
            - php

    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: symfony
        ports:
            - "3333:3306"


            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8890:801"
        environment:
          - PMA_HOST=mysql
          - PMA_USER=root
          - PMA_PASSWORD=symfony